#!/bin/bash

# author Max Henny
# Personal config script for Ultramarine linux

#initial updates
echo "Running Initial Updates"
sudo dnf update -y
sudo flatpak update -y

# Dnf installations
echo 'DNF installations'
sudo dnf install vlc tmux tldr yakuake tmux-powerline powerline vim-powerline -y


# Flatpak apps installations
# Apps in order, discord, telegram, spotify, obsidian,bitwarden, krita, warehouse, shortwave, flatseal, gearlever, vscode

echo 'Flatpak App Install'
sudo flatpak install com.discordapp.Discord org.telegram.desktop com.spotify.Client md.obsidian.Obsidian com.bitwarden.desktop org.kde.krita io.github.flattool.Warehouse de.haeckerfelix.Shortwave com.github.tchx84.Flatseal it.mijorus.gearlever com.visualstudio.code -y

# Flatpak game installations
# Apps in order, protonup-qt, protontricks, retroarch, limo
sudo flatpak install net.davidotek.pupgui2 com.github.Matoking.protontricks io.github.limo_app.limo -y

# Add repos mullvad

# mullvad feb2026
# Fedora 41 and newer
# Add the Mullvad repository server to dnf
sudo dnf config-manager addrepo --from-repofile=https://repository.mullvad.net/rpm/stable/mullvad.repo

# install
sudo dnf update -y
sudo dnf install mullvad-vpn -y


# Tmux Autostart Config
# from mark hansen https://www.markhansen.co.nz/auto-start-tmux/

echo '# Tmux Autostart script by mark hansen' >> ~/.zshrc
echo 'if [ -n "$PS1" ] && [ -z "$TMUX" ]; then' >> ~/.zshrc
echo '  tmux new-session -A -s main' >> ~/.zshrc
echo 'fi' >> ~/.zshrc

# Enables tmux-powerline
echo 'source /usr/share/tmux/powerline.conf' >> ~/.tmux.conf

# Add Telegram Desktop, Yakuake, and Mullvad VPN to KDE autostart
# Section generated by cursor - untested
echo "Adding Telegram Desktop, Yakuake, and Mullvad VPN to KDE autostart"

# Create KDE autostart directory if it doesn't exist
mkdir -p ~/.config/autostart

# Create Telegram Desktop autostart entry
cat << EOF > ~/.config/autostart/1org.telegram.desktop.desktop
[Desktop Entry]
Exec=flatpak run --command=telegram-desktop org.telegram.desktop -autostart
Name=org.telegram.desktop
Type=Application
X-Flatpak=org.telegram.desktop
EOF

# Create Yakuake autostart entry
cat << EOF > ~/.config/autostart/1org.kde.yakuake.desktop
[Desktop Entry]
Categories=Qt;KDE;System;TerminalEmulator;
Comment=A drop-down terminal emulator based on KDE Konsole technology.
DBusActivatable=true
Exec=yakuake
GenericName=Drop-down Terminal
Icon=yakuake
Name=Yakuake
StartupNotify=false
Terminal=false
Type=Application
EOF

# Create Mullvad VPN autostart entry
cat << EOF > ~/.config/autostart/1net.mullvad.MullvadVPN.desktop
[Desktop Entry]
Name=Mullvad VPN
Exec="/opt/Mullvad VPN/mullvad-vpn" %U
Terminal=false
Type=Application
Icon=mullvad-vpn
StartupWMClass=Mullvad VPN
Comment=Mullvad VPN client
Categories=Network;
EOF

echo "Telegram Desktop, Yakuake, and Mullvad VPN added to KDE autostart"

echo 'Complete'

#oh-my zsh
echo "Installing oh-my-zsh this will exit out of script on completion"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
